name: Meu Action Exemplo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Usar minha ação customizada
      uses: Karrary37/poc-github-action@VS-0.11
      with:
        teste-1-message: 'Oi, mundo!'
        teste-2-message: 'Ola, mundo!'