name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Usar minha ação customizada
      uses: Karrary37/poc-github-action@master
      with:
        argumento1: 'valor1'
        argumento2: 'valor2'